In [2]:
import pandas as pd

df = pd.read_pickle('../data/aviasales_dataset_in_rubles_with_months(1).pkl')

df.head()

,depart_date,origin,destination,gate,return_date,found_at,trip_class,value,number_of_changes,duration,distance,show_to_affiliates,actual
0,2026-06-02,MOW,LED,Kupi.com,,2026-05-19T20:34:30Z,0,3379,0,90,598,True,True
1,2026-06-03,MOW,LED,Kupi.com,,2026-05-19T21:03:50Z,0,3379,0,90,624,True,True
2,2026-06-23,MOW,LED,Kupi.com,,2026-05-19T19:14:42Z,0,3879,0,85,598,True,True
3,2026-06-01,MOW,LED,Kupi.com,,2026-05-19T21:19:01Z,0,3879,0,90,598,True,True
4,2026-06-08,MOW,LED,Т-Банк,,2026-05-19T20:48:10Z,0,3879,0,85,598,True,True

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36528 entries, 0 to 36527
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   depart_date         36528 non-null  str
 1   origin              36528 non-null  str
 2   destination         36528 non-null  str
 3   gate                36528 non-null  str
 4   return_date         36528 non-null  str
 5   found_at            36528 non-null  str
 6   trip_class          36528 non-null  int64
 7   value               36528 non-null  int64
 8   number_of_changes   36528 non-null  int64
 9   duration            36528 non-null  int64
 10  distance            36528 non-null  int64
 11  show_to_affiliates  36528 non-null  bool
 12  actual              36528 non-null  bool
dtypes: bool(2), int64(5), str(6)
memory usage: 4.7 MB

In [4]:
df.describe()

,trip_class,value,number_of_changes,duration,distance
count,36528.0,36528.000000,36528.000000,36528.000000,36528.000000
mean,0.0,21205.290654,0.801029,861.788737,2911.376205
std,0.0,12999.457680,0.777836,806.981619,2702.816287
min,0.0,853.000000,0.000000,0.000000,0.000000
25%,0.0,11448.750000,0.000000,120.000000,813.000000
50%,0.0,19552.000000,1.000000,715.000000,2136.000000
75%,0.0,29735.750000,1.000000,1435.000000,4296.000000
max,0.0,302659.000000,5.000000,5705.000000,10448.000000

In [5]:
df.columns.to_list()

['depart_date',
 'origin',
 'destination',
 'gate',
 'return_date',
 'found_at',
 'trip_class',
 'value',
 'number_of_changes',
 'duration',
 'distance',
 'show_to_affiliates',
 'actual']

In [6]:
df.isna().sum()

depart_date           0
origin                0
destination           0
gate                  0
return_date           0
found_at              0
trip_class            0
value                 0
number_of_changes     0
duration              0
distance              0
show_to_affiliates    0
actual                0
dtype: int64

In [7]:
(df == 0).sum()

depart_date               0
origin                    0
destination               0
gate                      0
return_date               0
found_at                  0
trip_class            36528
value                     0
number_of_changes     14681
duration               6978
distance               6978
show_to_affiliates        0
actual                    0
dtype: int64

In [8]:
def data_preprocessing(data):
    df_clean = data.copy()
    columns_to_drop = ['gate', 'return_date', 'trip_class', 'show_to_affiliates', 'actual']
    df_clean.drop(columns=columns_to_drop, inplace=True)
    print(f"Колонки: {', '.join(columns_to_drop)} удалены, так как не содержат полезной информации")
    columns_to_clean = ['duration', 'distance']
    for cols in columns_to_clean:
        df_clean = df_clean[df_clean[cols] > 0]
    df_clean = df_clean.reset_index(drop=True)
    print(f"Колонки: {', '.join(columns_to_clean)} очищены от нулевых значений")
    return df_clean

clean_data = data_preprocessing(df)
clean_data.describe()

Колонки: gate, return_date, trip_class, show_to_affiliates, actual удалены, так как не содержат полезной информации
Колонки: duration, distance очищены от нулевых значений

               value  number_of_changes      duration      distance
count   29550.000000       29550.000000  29550.000000  29550.000000
mean    21661.457056           0.990186   1065.293367   3598.874788
std     13117.825811           0.748732    766.945494   2560.476217
min       853.000000           0.000000     60.000000    255.000000
25%     11974.000000           0.000000    335.000000   1748.000000
50%     20176.000000           1.000000    970.000000   2500.000000
75%     29964.000000           1.000000   1600.000000   5815.000000
max    302659.000000           5.000000   5705.000000  10448.000000

In [9]:
clean_data.head(10)

,depart_date,origin,destination,found_at,value,number_of_changes,duration,distance
0,2026-06-02,MOW,LED,2026-05-19T20:34:30Z,3379,0,90,598
1,2026-06-03,MOW,LED,2026-05-19T21:03:50Z,3379,0,90,624
2,2026-06-23,MOW,LED,2026-05-19T19:14:42Z,3879,0,85,598
3,2026-06-01,MOW,LED,2026-05-19T21:19:01Z,3879,0,90,598
4,2026-06-08,MOW,LED,2026-05-19T20:48:10Z,3879,0,85,598
5,2026-06-09,MOW,LED,2026-05-19T21:16:24Z,3879,0,90,624
6,2026-06-24,MOW,LED,2026-05-19T20:47:28Z,3879,0,90,598
7,2026-06-06,MOW,LED,2026-05-19T20:26:35Z,3879,0,90,624
8,2026-06-04,MOW,LED,2026-05-19T21:18:57Z,3880,0,90,598
9,2026-06-29,MOW,LED,2026-05-19T18:47:05Z,4074,0,231,634

In [24]:
def feature_engineering(data):
    processed_df = data.copy()
    processed_df['depart_date'] = pd.to_datetime(processed_df['depart_date'], utc=True)
    processed_df['found_at'] = pd.to_datetime(processed_df['found_at'], utc=True)
    processed_df['departure_day_of_week'] = processed_df['depart_date'].dt.dayofweek
    processed_df['departure_day'] = processed_df['depart_date'].dt.day
    processed_df['departure_month'] = processed_df['depart_date'].dt.month
    processed_df['departure_year'] = processed_df['depart_date'].dt.year
    processed_df['time_diff'] = processed_df['depart_date'] - processed_df['found_at']
    processed_df['days_to_departure'] = processed_df['time_diff'].dt.days
    processed_df.drop(columns=['depart_date', 'found_at', 'time_diff'], inplace=True)
    bins_season = [0, 2, 5, 8, 11, 12]
    labels_season = ["Winter", "Spring", "Summer", "Autumn", "Winter"]
    processed_df['season'] = pd.cut(processed_df['departure_month'], bins=bins_season, labels=labels_season, ordered=False)
    processed_df['is_weekend'] = (processed_df['departure_day_of_week'] >= 5).astype(int)
    processed_df['departure_year'] = processed_df['departure_year'] - 2026
    if 'departure_day' in processed_df.columns:
        bins = [0, 10, 20, 32]
        month_parts = ['start', 'middle', 'end']
        processed_df['month_part'] = pd.cut(processed_df['departure_day'], bins=bins, labels=month_parts)
        processed_df.drop(columns='departure_day', inplace=True)
    return processed_df

data_with_features = feature_engineering(clean_data)
data_with_features.head(10)

,origin,destination,value,number_of_changes,duration,distance,departure_day_of_week,departure_month,departure_year,days_to_departure,season,is_weekend,month_part
0,MOW,LED,3379,0,90,598,1,6,0,13,Summer,0,start
1,MOW,LED,3379,0,90,624,2,6,0,14,Summer,0,start
2,MOW,LED,3879,0,85,598,1,6,0,34,Summer,0,end
3,MOW,LED,3879,0,90,598,0,6,0,12,Summer,0,start
4,MOW,LED,3879,0,85,598,0,6,0,19,Summer,0,start
5,MOW,LED,3879,0,90,624,1,6,0,20,Summer,0,start
6,MOW,LED,3879,0,90,598,2,6,0,35,Summer,0,end
7,MOW,LED,3879,0,90,624,5,6,0,17,Summer,1,start
8,MOW,LED,3880,0,90,598,3,6,0,15,Summer,0,start
9,MOW,LED,4074,0,231,634,0,6,0,40,Summer,0,end

In [15]:
import json
data_to_search = data_with_features.copy()
distance_duration = data_to_search.groupby(['origin', 'destination']).agg({
    'distance': 'min',
    'duration': 'min'
}).to_dict(orient='index')
routes_to_json = {
    f'{origin}-{destination}': metrics
    for (origin, destination), metrics in distance_duration.items()
}
with open('../data/routes_data.json', 'w', encoding='utf-8') as f:
    json.dump(routes_to_json, f,ensure_ascii=False, indent=4)

print('Данные успешно сохранены в routes_data.json')

Данные успешно сохранены в routes_data.json

In [16]:
origins = set()
for arr in distance_duration.keys():
   origins.add(arr[0])
print(origins)

{'LON', 'MOW', 'PAR', 'AER', 'DXB', 'BCN', 'BKK', 'AYT', 'BEG', 'AMS', 'HKT', 'BJS', 'TBS', 'FRA', 'DOH', 'IST', 'SHJ', 'LED', 'GRO', 'TYO'}

In [17]:
import mlflow.sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error



X = data_with_features.copy()
X.drop(columns='value', inplace=True)
y = data_with_features['value']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
ohe = OneHotEncoder(sparse_output=False, drop='first', handle_unknown='error')
cols_to_normalize = ['duration', 'distance', 'days_to_departure']
cols_to_one_hot_encode = ['month_part', 'departure_month', 'departure_day_of_week', 'origin', 'destination', 'season']
encoded_train_arr = ohe.fit_transform(X_train[cols_to_one_hot_encode])
encoded_train_df = pd.DataFrame(
    encoded_train_arr,
    columns=ohe.get_feature_names_out(cols_to_one_hot_encode),
    index=X_train.index
)
encoded_test_arr = ohe.transform((X_test[cols_to_one_hot_encode]))
encoded_test_df = pd.DataFrame(
    encoded_test_arr,
    columns=ohe.get_feature_names_out(cols_to_one_hot_encode),
    index=X_test.index
)
X_train[cols_to_normalize] = X_train[cols_to_normalize].astype(float)
X_test[cols_to_normalize] = X_test[cols_to_normalize].astype(float)
X_train.loc[:, cols_to_normalize] = scaler.fit_transform(X_train[cols_to_normalize])
X_test.loc[:, cols_to_normalize] = scaler.transform(X_test[cols_to_normalize])
X_train_final = X_train.drop(columns=cols_to_one_hot_encode).join(encoded_train_df)
X_test_final = X_test.drop(columns=cols_to_one_hot_encode).join(encoded_test_df)
X_train_final.columns.to_list()


linear_reg_baseline = Ridge(alpha=1.0)
linear_reg_baseline.fit(X_train_final, y_train)
preds_linaer_reg = linear_reg_baseline.predict(X_test_final)
print(f'MAE: {mean_absolute_error(y_test, preds_linaer_reg):.2f}')
print(f'MAPE: {(mean_absolute_percentage_error(y_test,preds_linaer_reg)*100):.2f}%')

MAE: 4293.28
MAPE: 29.05%

In [31]:
import joblib
joblib.dump(scaler, '../models/scaler.pkl')
joblib.dump(ohe, '../models/one_hot_encoder.pkl')
print('Scaler и OneHotEncoder загружены')

Scaler и OneHotEncoder загружены

In [39]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
mlflow.set_experiment('flight_price_prediction')
with mlflow.start_run():
    rf_model = RandomForestRegressor(random_state=42, n_jobs=-1)
    param_grid = {
        'n_estimators': [50, 100, 200],
        'max_depth': [None, 10, 15]
    }

    grid_search = GridSearchCV(
        estimator=rf_model,
        param_grid=param_grid,
        cv=5,
        scoring='neg_mean_absolute_error',
        n_jobs=-1,
        verbose=2
    )

    print('Начинаем поиск лучших параметров')
    grid_search.fit(X_train_final, y_train)
    print('Поиск завершен')
    mlflow.log_params(grid_search.best_params_)
    print(f'Лучшие параметры RandomForest: {grid_search.best_params_}')
    print(f'Лучший MAE на CV: {-grid_search.best_score_:.2f}')
    preds_rf = grid_search.predict(X_test_final)
    mae_rf = mean_absolute_error(y_test, preds_rf)
    mape_rf = mean_absolute_percentage_error(y_test, preds_rf)
    mlflow.log_metric('MAE', mae_rf)
    mlflow.log_metric('MAPE', mape_rf)
    mlflow.sklearn.log_model(grid_search.best_estimator_, name="model", serialization_format='skops')
    print(f'MAE: {mae_rf:.2f}')
    print(f'MAPE: {(mape_rf*100):.2f}%')

2026/05/30 22:09:44 INFO mlflow.tracking.fluent: Experiment with name 'flight_price_prediction' does not exist. Creating a new experiment.

Начинаем поиск лучших параметров
Fitting 5 folds for each of 9 candidates, totalling 45 fits
[CV] END ....................max_depth=None, n_estimators=50; total time=   2.9s
[CV] END ....................max_depth=None, n_estimators=50; total time=   3.7s
[CV] END ....................max_depth=None, n_estimators=50; total time=   4.2s
[CV] END ....................max_depth=None, n_estimators=50; total time=   4.4s
[CV] END ....................max_depth=None, n_estimators=50; total time=   4.2s
[CV] END ...................max_depth=None, n_estimators=100; total time=   8.7s
[CV] END ...................max_depth=None, n_estimators=100; total time=   8.8s
[CV] END ...................max_depth=None, n_estimators=100; total time=   9.1s
[CV] END ...................max_depth=None, n_estimators=100; total time=   9.1s
[CV] END ...................max_depth=None, n_estimators=100; total time=   9.3s
[CV] END ......................max_depth=10, n_estimators=50; total time=   2.2s
[CV] END ......................max_depth=10, n_estimators=50; total time=   2.5s
[CV] END ......................max_depth=10, n_estimators=50; total time=   2.3s
[CV] END ......................max_depth=10, n_estimators=50; total time=   2.5s
[CV] END ......................max_depth=10, n_estimators=50; total time=   2.8s
[CV] END .....................max_depth=10, n_estimators=100; total time=   4.7s
[CV] END .....................max_depth=10, n_estimators=100; total time=   4.8s
[CV] END .....................max_depth=10, n_estimators=100; total time=   4.6s
[CV] END .....................max_depth=10, n_estimators=100; total time=   4.7s
[CV] END .....................max_depth=10, n_estimators=100; total time=   4.8s
[CV] END ...................max_depth=None, n_estimators=200; total time=  18.3s
[CV] END ...................max_depth=None, n_estimators=200; total time=  18.3s
[CV] END ...................max_depth=None, n_estimators=200; total time=  18.3s
[CV] END ...................max_depth=None, n_estimators=200; total time=  18.8s
[CV] END ...................max_depth=None, n_estimators=200; total time=  19.0s
[CV] END ......................max_depth=15, n_estimators=50; total time=   3.6s
[CV] END .....................max_depth=10, n_estimators=200; total time=   9.6s
[CV] END ......................max_depth=15, n_estimators=50; total time=   3.5s
[CV] END ......................max_depth=15, n_estimators=50; total time=   3.7s
[CV] END ......................max_depth=15, n_estimators=50; total time=   3.6s
[CV] END .....................max_depth=10, n_estimators=200; total time=   9.8s
[CV] END .....................max_depth=10, n_estimators=200; total time=   9.9s
[CV] END .....................max_depth=10, n_estimators=200; total time=  10.2s
[CV] END ......................max_depth=15, n_estimators=50; total time=   3.6s
[CV] END .....................max_depth=10, n_estimators=200; total time=  10.1s
[CV] END .....................max_depth=15, n_estimators=100; total time=   7.1s
[CV] END .....................max_depth=15, n_estimators=100; total time=   6.9s
[CV] END .....................max_depth=15, n_estimators=100; total time=   6.9s
[CV] END .....................max_depth=15, n_estimators=100; total time=   6.7s
[CV] END .....................max_depth=15, n_estimators=100; total time=   6.7s
[CV] END .....................max_depth=15, n_estimators=200; total time=   9.8s
[CV] END .....................max_depth=15, n_estimators=200; total time=   9.8s
[CV] END .....................max_depth=15, n_estimators=200; total time=   9.8s
[CV] END .....................max_depth=15, n_estimators=200; total time=   9.6s
[CV] END .....................max_depth=15, n_estimators=200; total time=   9.0s
Поиск завершен
Лучшие параметры RandomForest: {'max_depth': None, 'n_estimators': 200}
Лучший MAE на CV: 1915.61
MAE: 1735.92
MAPE: 9.56%

In [42]:
from catboost import CatBoostRegressor
mlflow.set_experiment('flight_price_prediction')
with mlflow.start_run():
    cat_model = CatBoostRegressor(
        random_state=42,
        verbose=False
    )
    param_grid = {
        'iterations': [1000, 2000, 3000],
        'max_depth': [6, 8, 10],
        'learning_rate': [0.1, 0.01, 0.001]
    }
    grid_search_catboost = GridSearchCV(
        estimator=cat_model,
        param_grid=param_grid,
        cv=5,
        scoring='neg_mean_absolute_error',
        n_jobs=-1
    )

    print('Начинаем поиск лучших параметров')
    grid_search_catboost.fit(X_train_final, y_train)
    cat_preds = grid_search_catboost.predict(X_test_final)
    print('Поиск завершен')
    print(f'Лучшие параметры catboost: {grid_search_catboost.best_params_}')
    print(f'Лучший MAE на CV: {-grid_search_catboost.best_score_:.2f}')
    mae_catboost = mean_absolute_error(y_test, cat_preds)
    mape_catboost = mean_absolute_percentage_error(y_test, cat_preds)
    print(f'MAE: {mae_catboost:.2f}')
    print(f'MAPE: {(mape_catboost*100):.2f}%')
    mlflow.catboost.log_model(grid_search_catboost.best_estimator_)
    mlflow.log_params(grid_search_catboost.best_params_)
    mlflow.log_metric("MAE", mae_catboost)
    mlflow.log_metric("MAPE", mape_catboost)

Начинаем поиск лучших параметров

/Users/mac/PyCharmMiscProject/.venv/lib/python3.14/site-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Поиск завершен
Лучшие параметры catboost: {'iterations': 3000, 'learning_rate': 0.1, 'max_depth': 8}
Лучший MAE на CV: 1865.81
MAE: 1743.09
MAPE: 9.75%

In [ ]:
best_model = grid_search_catboost.best_estimator_
best_model.save_model('flight_price_predictor.cbm')
print('Модель успешно сохранена в flight_price_predictor.cbm')

In [43]:
import lightgbm as lgb
mlflow.set_experiment('flight_price_prediction')
with mlflow.start_run():
    lgb_model = lgb.LGBMRegressor(
        random_state=42,
        verbose=-1,
        n_jobs=1
    )

    param_grid = {
        'n_estimators': [1000, 2000, 3000],
        'max_depth': [6, 8, 10],
        'learning_rate': [0.1, 0.05, 0.01]
    }
    grid_search_lgb = GridSearchCV(
        estimator=lgb_model,
        param_grid=param_grid,
        cv=5,
        scoring='neg_mean_absolute_error',
        n_jobs=-1
    )
    print('Начинаем подбор гиперпараметров')
    grid_search_lgb.fit(X_train_final, y_train)
    print('Подбор завершен')
    preds_lgb = grid_search_lgb.predict(X_test_final)
    mae_lgb = mean_absolute_error(y_test, preds_lgb)
    mape_lgb = mean_absolute_percentage_error(y_test, preds_lgb)
    print(f'Лучшие параметры LightGBM: {grid_search_lgb.best_params_}')
    print(f'Лучший MAE на CV: {-grid_search_lgb.best_score_:.2f}')
    print(f'MAE: {mae_lgb:.2f}')
    print(f'MAPE: {(mape_lgb*100):.2f}%')
    mlflow.lightgbm.log_model(grid_search_lgb.best_estimator_, name='lightgbm')
    mlflow.log_params(grid_search_lgb.best_params_)
    mlflow.log_metric("MAE", mae_lgb)
    mlflow.log_metric("MAPE", mape_lgb)

Начинаем подбор гиперпараметров
Подбор завершен

2026/05/30 22:54:32 WARNING mlflow.lightgbm: Saving the models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

Лучшие параметры LightGBM: {'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 3000}
Лучший MAE на CV: 1960.85
MAE: 1785.55
MAPE: 10.05%